import {
  Ruler,
  Weight,
  Thermometer,
  Square,
  Droplets,
  Gauge,
  Clock,
  ArrowDownUp,
  Zap,
  Activity,
  Radio,
  RotateCcw,
  HardDrive,
  Fuel,
  Binary,
  Hash,
  FlaskConical,
  Divide,
  Percent,
  Palette,
  Paintbrush,
  Blend,
  ScanEye,
  Eye,
  Globe,
  Timer,
  CalendarClock,
  CalendarDays,
  Cake,
  Braces,
  FileSpreadsheet,
  FileCode,
  FileJson,
  FileText,
  Table,
  Code,
  Database,
  RectangleHorizontal,
  Scaling,
  Maximize,
  Laptop,
  Scissors,
  Repeat,
  UtensilsCrossed,
  ChefHat,
  Flame,
  MapPin,
  Navigation,
  type LucideIcon,
} from "lucide-react";

export type ConverterCategory =
  | "unit"
  | "number"
  | "color"
  | "datetime"
  | "data"
  | "css"
  | "cooking"
  | "geography";

export type ConverterInputType =
  | "unit"
  | "color"
  | "dualColor"
  | "code"
  | "datetime"
  | "text";

export interface ConverterToolDefinition {
  slug: string;
  title: string;
  description: string;
  icon: LucideIcon;
  emoji: string;
  category: ConverterCategory;
  inputType: ConverterInputType;
  dualInput?: boolean;
  placeholder?: string;
}

export const tools: ConverterToolDefinition[] = [
  // ── Unit ──────────────────────────────────────────────
  {
    slug: "length",
    title: "Length Converter",
    description: "Convert between meters, kilometers, miles, feet, inches, and more.",
    icon: Ruler,
    emoji: "📏",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "weight",
    title: "Weight Converter",
    description: "Convert between kilograms, pounds, ounces, tons, and more.",
    icon: Weight,
    emoji: "⚖️",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "temperature",
    title: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin.",
    icon: Thermometer,
    emoji: "🌡️",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "area",
    title: "Area Converter",
    description: "Convert between square meters, hectares, acres, square feet, and more.",
    icon: Square,
    emoji: "📐",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "volume",
    title: "Volume Converter",
    description: "Convert between liters, gallons, cups, fluid ounces, and more.",
    icon: Droplets,
    emoji: "🧪",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "speed",
    title: "Speed Converter",
    description: "Convert between m/s, km/h, mph, knots, and more.",
    icon: Gauge,
    emoji: "🏎️",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "time",
    title: "Time Converter",
    description: "Convert between seconds, minutes, hours, days, weeks, and more.",
    icon: Clock,
    emoji: "⏱️",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "pressure",
    title: "Pressure Converter",
    description: "Convert between Pascal, bar, PSI, atmosphere, and more.",
    icon: ArrowDownUp,
    emoji: "🔩",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "energy",
    title: "Energy Converter",
    description: "Convert between joules, calories, kilowatt-hours, BTU, and more.",
    icon: Zap,
    emoji: "⚡",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "power",
    title: "Power Converter",
    description: "Convert between watts, kilowatts, horsepower, and more.",
    icon: Activity,
    emoji: "🔌",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "frequency",
    title: "Frequency Converter",
    description: "Convert between hertz, kilohertz, megahertz, gigahertz, and RPM.",
    icon: Radio,
    emoji: "📻",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "angle",
    title: "Angle Converter",
    description: "Convert between degrees, radians, gradians, and turns.",
    icon: RotateCcw,
    emoji: "📐",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "data-storage",
    title: "Data Storage Converter",
    description: "Convert between bytes, kilobytes, megabytes, gigabytes, and more.",
    icon: HardDrive,
    emoji: "💾",
    category: "unit",
    inputType: "unit",
  },
  {
    slug: "fuel-economy",
    title: "Fuel Economy Converter",
    description: "Convert between km/L, mpg, and L/100km.",
    icon: Fuel,
    emoji: "⛽",
    category: "unit",
    inputType: "unit",
  },

  // ── Number ───────────────────────────────────────────
  {
    slug: "number-base",
    title: "Number Base Converter",
    description: "Convert between binary, octal, decimal, hexadecimal, and custom bases.",
    icon: Binary,
    emoji: "🔢",
    category: "number",
    inputType: "text",
    placeholder: "255",
  },
  {
    slug: "roman-numeral",
    title: "Roman Numeral Converter",
    description: "Convert between Roman numerals and Arabic numbers.",
    icon: Hash,
    emoji: "🏛️",
    category: "number",
    inputType: "text",
    placeholder: "42 or XIV",
  },
  {
    slug: "scientific-notation",
    title: "Scientific Notation Converter",
    description: "Convert between scientific notation and standard numbers.",
    icon: FlaskConical,
    emoji: "🔬",
    category: "number",
    inputType: "text",
    placeholder: "1500000 or 1.5e6",
  },
  {
    slug: "fraction-decimal",
    title: "Fraction ↔ Decimal",
    description: "Convert between fractions and decimal numbers.",
    icon: Divide,
    emoji: "➗",
    category: "number",
    inputType: "text",
    placeholder: "3/4 or 0.75",
  },
  {
    slug: "percentage",
    title: "Percentage Converter",
    description: "Convert between fractions, decimals, and percentages.",
    icon: Percent,
    emoji: "%",
    category: "number",
    inputType: "text",
    placeholder: "0.75 or 3/4",
  },

  // ── Color ────────────────────────────────────────────
  {
    slug: "color-converter",
    title: "Color Converter",
    description: "Convert between HEX, RGB, HSL, HSV, and CMYK color formats.",
    icon: Palette,
    emoji: "🎨",
    category: "color",
    inputType: "color",
  },
  {
    slug: "color-palette-generator",
    title: "Color Palette Generator",
    description: "Generate complementary, triadic, and analogous color palettes.",
    icon: Paintbrush,
    emoji: "🖌️",
    category: "color",
    inputType: "color",
  },
  {
    slug: "gradient-generator",
    title: "CSS Gradient Generator",
    description: "Create linear, radial, and conic CSS gradients with live preview.",
    icon: Blend,
    emoji: "🌈",
    category: "color",
    inputType: "dualColor",
  },
  {
    slug: "color-contrast-checker",
    title: "Color Contrast Checker",
    description: "Check WCAG AA/AAA color contrast ratio between two colors.",
    icon: ScanEye,
    emoji: "👁️",
    category: "color",
    inputType: "dualColor",
  },
  {
    slug: "color-blindness-simulator",
    title: "Color Blindness Simulator",
    description: "Simulate how colors appear to people with color vision deficiency.",
    icon: Eye,
    emoji: "👓",
    category: "color",
    inputType: "color",
  },

  // ── DateTime ─────────────────────────────────────────
  {
    slug: "timezone",
    title: "Timezone Converter",
    description: "Convert time between different timezones worldwide.",
    icon: Globe,
    emoji: "🌍",
    category: "datetime",
    inputType: "datetime",
  },
  {
    slug: "unix-timestamp",
    title: "Unix Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates.",
    icon: Timer,
    emoji: "🕐",
    category: "datetime",
    inputType: "text",
    placeholder: "1705312200 or 2024-01-15",
  },
  {
    slug: "date-format",
    title: "Date Format Converter",
    description: "Convert dates between different formats (ISO, US, EU, and more).",
    icon: CalendarClock,
    emoji: "📅",
    category: "datetime",
    inputType: "text",
    placeholder: "2024-01-15 or 01/15/2024",
  },
  {
    slug: "date-calculator",
    title: "Date Calculator",
    description: "Calculate the difference between dates or add/subtract days.",
    icon: CalendarDays,
    emoji: "🗓️",
    category: "datetime",
    inputType: "datetime",
  },
  {
    slug: "age-calculator",
    title: "Age Calculator",
    description: "Calculate exact age from birth date in years, months, and days.",
    icon: Cake,
    emoji: "🎂",
    category: "datetime",
    inputType: "datetime",
  },

  // ── Data ─────────────────────────────────────────────
  {
    slug: "json-yaml",
    title: "JSON ↔ YAML",
    description: "Convert between JSON and YAML data formats.",
    icon: Braces,
    emoji: "📋",
    category: "data",
    inputType: "code",
  },
  {
    slug: "json-csv",
    title: "JSON ↔ CSV",
    description: "Convert between JSON arrays and CSV spreadsheet format.",
    icon: FileSpreadsheet,
    emoji: "📊",
    category: "data",
    inputType: "code",
  },
  {
    slug: "json-xml",
    title: "JSON ↔ XML",
    description: "Convert between JSON and XML data formats.",
    icon: FileCode,
    emoji: "📄",
    category: "data",
    inputType: "code",
  },
  {
    slug: "json-toml",
    title: "JSON ↔ TOML",
    description: "Convert between JSON and TOML configuration formats.",
    icon: FileJson,
    emoji: "⚙️",
    category: "data",
    inputType: "code",
  },
  {
    slug: "markdown-html",
    title: "Markdown ↔ HTML",
    description: "Convert between Markdown and HTML markup.",
    icon: FileText,
    emoji: "📝",
    category: "data",
    inputType: "code",
  },
  {
    slug: "csv-table",
    title: "CSV to Table",
    description: "Convert CSV data to Markdown or HTML tables.",
    icon: Table,
    emoji: "📊",
    category: "data",
    inputType: "code",
  },
  {
    slug: "json-typescript",
    title: "JSON to TypeScript",
    description: "Generate TypeScript interfaces from JSON data.",
    icon: Code,
    emoji: "🔷",
    category: "data",
    inputType: "code",
  },
  {
    slug: "sql-json",
    title: "SQL ↔ JSON",
    description: "Convert between SQL INSERT statements and JSON data.",
    icon: Database,
    emoji: "🗃️",
    category: "data",
    inputType: "code",
  },

  // ── CSS ──────────────────────────────────────────────
  {
    slug: "px-rem",
    title: "px ↔ rem Converter",
    description: "Convert between pixels and rem units with custom base size.",
    icon: RectangleHorizontal,
    emoji: "📐",
    category: "css",
    inputType: "unit",
  },
  {
    slug: "px-em",
    title: "px ↔ em Converter",
    description: "Convert between pixels and em units with custom parent size.",
    icon: Scaling,
    emoji: "🔤",
    category: "css",
    inputType: "unit",
  },
  {
    slug: "px-percent",
    title: "px ↔ % Converter",
    description: "Convert between pixels and percentage with custom container width.",
    icon: Maximize,
    emoji: "📏",
    category: "css",
    inputType: "unit",
  },
  {
    slug: "css-unit",
    title: "CSS Unit Converter",
    description: "Convert between px, rem, em, %, vw, vh and other CSS units.",
    icon: Laptop,
    emoji: "💻",
    category: "css",
    inputType: "unit",
  },
  {
    slug: "css-minifier",
    title: "CSS Minifier / Beautifier",
    description: "Minify or beautify CSS code for production or readability.",
    icon: Scissors,
    emoji: "✂️",
    category: "css",
    inputType: "code",
  },
  {
    slug: "tailwind-css",
    title: "Tailwind ↔ CSS",
    description: "Convert between Tailwind CSS classes and vanilla CSS.",
    icon: Repeat,
    emoji: "🎨",
    category: "css",
    inputType: "code",
  },

  // ── Cooking ──────────────────────────────────────────
  {
    slug: "cooking-measurement",
    title: "Cooking Measurement Converter",
    description: "Convert between cups, tablespoons, teaspoons, milliliters, and grams.",
    icon: UtensilsCrossed,
    emoji: "🍳",
    category: "cooking",
    inputType: "unit",
  },
  {
    slug: "recipe-scaler",
    title: "Recipe Scaler",
    description: "Scale recipe ingredients up or down by serving size.",
    icon: ChefHat,
    emoji: "👨‍🍳",
    category: "cooking",
    inputType: "text",
    placeholder: "2 cups flour\n1/2 tsp salt\n200g sugar",
  },
  {
    slug: "oven-temperature",
    title: "Oven Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Gas Mark for oven temperatures.",
    icon: Flame,
    emoji: "🔥",
    category: "cooking",
    inputType: "unit",
  },

  // ── Geography ────────────────────────────────────────
  {
    slug: "coordinate",
    title: "Coordinate Converter",
    description: "Convert between DMS, DD, and DDM coordinate formats.",
    icon: MapPin,
    emoji: "📍",
    category: "geography",
    inputType: "text",
    placeholder: "37.5665, 126.9780",
  },
  {
    slug: "distance-calculator",
    title: "Distance Calculator",
    description: "Calculate the distance between two geographic coordinates.",
    icon: Navigation,
    emoji: "🧭",
    category: "geography",
    inputType: "text",
    placeholder: "37.5665, 126.9780\n35.6762, 139.6503",
  },
];

export const categoryColors: Record<
  ConverterCategory,
  { bg: string; text: string; bgHover: string; textHover: string }
> = {
  unit: {
    bg: "bg-emerald-50 dark:bg-emerald-950/40",
    text: "text-emerald-600 dark:text-emerald-400",
    bgHover: "group-hover:bg-emerald-500",
    textHover: "group-hover:text-white",
  },
  number: {
    bg: "bg-blue-50 dark:bg-blue-950/40",
    text: "text-blue-600 dark:text-blue-400",
    bgHover: "group-hover:bg-blue-500",
    textHover: "group-hover:text-white",
  },
  color: {
    bg: "bg-violet-50 dark:bg-violet-950/40",
    text: "text-violet-600 dark:text-violet-400",
    bgHover: "group-hover:bg-violet-500",
    textHover: "group-hover:text-white",
  },
  datetime: {
    bg: "bg-orange-50 dark:bg-orange-950/40",
    text: "text-orange-600 dark:text-orange-400",
    bgHover: "group-hover:bg-orange-500",
    textHover: "group-hover:text-white",
  },
  data: {
    bg: "bg-cyan-50 dark:bg-cyan-950/40",
    text: "text-cyan-600 dark:text-cyan-400",
    bgHover: "group-hover:bg-cyan-500",
    textHover: "group-hover:text-white",
  },
  css: {
    bg: "bg-pink-50 dark:bg-pink-950/40",
    text: "text-pink-600 dark:text-pink-400",
    bgHover: "group-hover:bg-pink-500",
    textHover: "group-hover:text-white",
  },
  cooking: {
    bg: "bg-amber-50 dark:bg-amber-950/40",
    text: "text-amber-600 dark:text-amber-400",
    bgHover: "group-hover:bg-amber-500",
    textHover: "group-hover:text-white",
  },
  geography: {
    bg: "bg-teal-50 dark:bg-teal-950/40",
    text: "text-teal-600 dark:text-teal-400",
    bgHover: "group-hover:bg-teal-500",
    textHover: "group-hover:text-white",
  },
};

export const categories = [
  { key: "unit" as const, label: "Unit", emoji: "📏" },
  { key: "number" as const, label: "Number", emoji: "🔢" },
  { key: "color" as const, label: "Color", emoji: "🎨" },
  { key: "datetime" as const, label: "Date/Time", emoji: "📅" },
  { key: "data" as const, label: "Data", emoji: "📋" },
  { key: "css" as const, label: "CSS", emoji: "💻" },
  { key: "cooking" as const, label: "Cooking", emoji: "🍳" },
  { key: "geography" as const, label: "Geography", emoji: "🌍" },
];

const toolsBySlug = new Map(tools.map((t) => [t.slug, t]));

export function getToolBySlug(slug: string) {
  return toolsBySlug.get(slug);
}
