import {
  Maximize2,
  Crop,
  RotateCw,
  FlipHorizontal,
  Minimize2,
  ArrowRightLeft,
  FileImage,
  Image,
  ImagePlus,
  Palette,
  Type,
  Square,
  Grid3X3,
  Blend,
  Layers,
  Circle,
  User,
  Smile,
  Droplets,
  ImageDown,
  PenLine,
  Scissors,
  LayoutGrid,
  Sparkles,
  ScanSearch,
  Film,
  AppWindow,
  Code,
  Rainbow,
  QrCode,
  Pipette,
  CircleDot,
  Diamond,
  SunDim,
  Contrast,
  type LucideIcon,
} from "lucide-react";

export interface ImageToolDefinition {
  slug: string;
  title: string;
  description: string;
  icon: LucideIcon;
  emoji: string;
  category: "edit" | "convert" | "effects" | "compose" | "optimize" | "generate";
  acceptedTypes: string;
  multiFile?: boolean;
  comingSoon?: boolean;
}

const IMG_ALL = ".jpg,.jpeg,.png,.gif,.webp,.bmp,.svg,.ico";
const IMG_RASTER = ".jpg,.jpeg,.png,.gif,.webp,.bmp,.svg,.ico";

export const tools: ImageToolDefinition[] = [
  // ── Edit ──────────────────────────────────────────────
  {
    slug: "resize",
    title: "Resize Image",
    description: "Change image dimensions with precision controls.",
    icon: Maximize2,
    emoji: "📐",
    category: "edit",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "crop",
    title: "Crop Image",
    description: "Trim your image with aspect ratio presets.",
    icon: Crop,
    emoji: "✂️",
    category: "edit",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "rotate",
    title: "Rotate Image",
    description: "Rotate images by any angle.",
    icon: RotateCw,
    emoji: "🔄",
    category: "edit",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "flip",
    title: "Flip Image",
    description: "Mirror images horizontally or vertically.",
    icon: FlipHorizontal,
    emoji: "🪞",
    category: "edit",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "photo-editor",
    title: "Photo Editor",
    description: "All-in-one photo editing with crop, filters, text, and drawing.",
    icon: PenLine,
    emoji: "🎨",
    category: "edit",
    acceptedTypes: IMG_RASTER,
  },

  // ── Convert ──────────────────────────────────────────
  {
    slug: "jpg-to-png",
    title: "JPG to PNG",
    description: "Convert JPG images to PNG format with transparency support.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".jpg,.jpeg",
  },
  {
    slug: "png-to-jpg",
    title: "PNG to JPG",
    description: "Convert PNG images to JPG format for smaller file sizes.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".png",
  },
  {
    slug: "webp-to-jpg",
    title: "WEBP to JPG",
    description: "Convert WEBP images to widely compatible JPG format.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".webp",
  },
  {
    slug: "webp-to-png",
    title: "WEBP to PNG",
    description: "Convert WEBP images to PNG format.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".webp",
  },
  {
    slug: "jpg-to-webp",
    title: "JPG to WEBP",
    description: "Convert JPG to modern WEBP format for better compression.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".jpg,.jpeg",
  },
  {
    slug: "png-to-webp",
    title: "PNG to WEBP",
    description: "Convert PNG to WEBP format for smaller file sizes.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".png",
  },
  {
    slug: "svg-to-png",
    title: "SVG to PNG",
    description: "Rasterize SVG vector graphics to PNG images.",
    icon: FileImage,
    emoji: "🖼️",
    category: "convert",
    acceptedTypes: ".svg",
  },
  {
    slug: "svg-to-jpg",
    title: "SVG to JPG",
    description: "Rasterize SVG vector graphics to JPG images.",
    icon: FileImage,
    emoji: "🖼️",
    category: "convert",
    acceptedTypes: ".svg",
  },
  {
    slug: "gif-to-jpg",
    title: "GIF to JPG",
    description: "Extract the first frame of a GIF as a JPG image.",
    icon: Image,
    emoji: "🎞️",
    category: "convert",
    acceptedTypes: ".gif",
  },
  {
    slug: "bmp-to-jpg",
    title: "BMP to JPG",
    description: "Convert BMP images to compressed JPG format.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".bmp",
  },
  {
    slug: "bmp-to-png",
    title: "BMP to PNG",
    description: "Convert BMP images to PNG format.",
    icon: ArrowRightLeft,
    emoji: "🔄",
    category: "convert",
    acceptedTypes: ".bmp",
  },

  // ── Effects ──────────────────────────────────────────
  {
    slug: "grayscale",
    title: "Grayscale",
    description: "Convert images to black and white.",
    icon: Palette,
    emoji: "⬛",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "add-text",
    title: "Add Text",
    description: "Overlay text on your images with custom fonts and styles.",
    icon: Type,
    emoji: "✏️",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "add-border",
    title: "Add Border",
    description: "Add decorative borders to your images.",
    icon: Square,
    emoji: "🖼️",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "pixelate",
    title: "Pixelate Image",
    description: "Apply mosaic pixelation effect to images.",
    icon: Grid3X3,
    emoji: "🟦",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "blur",
    title: "Blur Image",
    description: "Apply gaussian blur effect with adjustable intensity.",
    icon: Blend,
    emoji: "🌫️",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "filters",
    title: "Image Filters",
    description: "Adjust brightness, contrast, saturation, and more.",
    icon: Sparkles,
    emoji: "✨",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "color-replace",
    title: "Color Replace",
    description: "Replace specific colors in your image.",
    icon: Pipette,
    emoji: "🎨",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "vignette",
    title: "Vignette",
    description: "Add a vignette darkening effect to edges.",
    icon: CircleDot,
    emoji: "🔲",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "noise",
    title: "Add Noise",
    description: "Add film grain and noise texture.",
    icon: Sparkles,
    emoji: "📺",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "sharpen",
    title: "Sharpen",
    description: "Enhance image sharpness and detail.",
    icon: Diamond,
    emoji: "🔍",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "sepia",
    title: "Sepia Tone",
    description: "Apply warm vintage sepia tone.",
    icon: SunDim,
    emoji: "🟤",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "invert",
    title: "Invert Colors",
    description: "Invert all colors in the image.",
    icon: Contrast,
    emoji: "🔄",
    category: "effects",
    acceptedTypes: IMG_RASTER,
  },

  // ── Compose ──────────────────────────────────────────
  {
    slug: "combine",
    title: "Combine Images",
    description: "Merge multiple images side by side or in a grid.",
    icon: Layers,
    emoji: "🧩",
    category: "compose",
    acceptedTypes: IMG_RASTER,
    multiFile: true,
  },
  {
    slug: "split-image",
    title: "Split Image",
    description: "Divide an image into a grid of equal parts.",
    icon: Scissors,
    emoji: "🔲",
    category: "compose",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "collage",
    title: "Collage Maker",
    description: "Create photo collages with customizable layouts.",
    icon: LayoutGrid,
    emoji: "🏞️",
    category: "compose",
    acceptedTypes: IMG_RASTER,
    multiFile: true,
  },
  {
    slug: "round-image",
    title: "Round Image",
    description: "Crop images into a perfect circle.",
    icon: Circle,
    emoji: "⭕",
    category: "compose",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "profile-photo",
    title: "Profile Photo Maker",
    description: "Create perfectly sized profile pictures for social media.",
    icon: User,
    emoji: "👤",
    category: "compose",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "meme",
    title: "Meme Generator",
    description: "Create memes with top and bottom text.",
    icon: Smile,
    emoji: "😂",
    category: "compose",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "image-to-icon",
    title: "Image to Icon",
    description: "Create favicon and app icons in multiple sizes.",
    icon: AppWindow,
    emoji: "🖼️",
    category: "compose",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "color-palette",
    title: "Color Palette",
    description: "Extract dominant colors from an image.",
    icon: Palette,
    emoji: "🎨",
    category: "compose",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "html-to-image",
    title: "HTML to Image",
    description: "Convert HTML and CSS code to an image.",
    icon: Code,
    emoji: "🌐",
    category: "compose",
    acceptedTypes: ".html,.htm,.xhtml,.svg,text/html",
  },

  // ── Generate ───────────────────────────────────────────
  {
    slug: "gradient",
    title: "Gradient Generator",
    description: "Create beautiful gradient images.",
    icon: Rainbow,
    emoji: "🌈",
    category: "generate",
    acceptedTypes: "",
  },
  {
    slug: "placeholder",
    title: "Placeholder Image",
    description: "Generate placeholder images for development.",
    icon: Image,
    emoji: "📐",
    category: "generate",
    acceptedTypes: "",
  },
  {
    slug: "pattern",
    title: "Pattern Generator",
    description: "Create seamless pattern images.",
    icon: Grid3X3,
    emoji: "🔳",
    category: "generate",
    acceptedTypes: "",
  },
  {
    slug: "qr-code",
    title: "QR Code Generator",
    description: "Generate QR codes from text or URLs.",
    icon: QrCode,
    emoji: "📱",
    category: "generate",
    acceptedTypes: "",
  },

  // ── Optimize ─────────────────────────────────────────
  {
    slug: "compress",
    title: "Compress Image",
    description: "Reduce image file size while preserving quality.",
    icon: Minimize2,
    emoji: "📦",
    category: "optimize",
    acceptedTypes: IMG_RASTER,
  },
  {
    slug: "watermark",
    title: "Watermark Image",
    description: "Add text or image watermarks with customizable opacity.",
    icon: Droplets,
    emoji: "💧",
    category: "optimize",
    acceptedTypes: IMG_RASTER,
  },

  // ── Server-required format conversions (comingSoon) ──
  {
    slug: "heic-to-jpg",
    title: "HEIC to JPG",
    description: "Convert iPhone HEIC photos to JPG format.",
    icon: ArrowRightLeft,
    emoji: "📱",
    category: "convert",
    acceptedTypes: ".heic,.heif",
    comingSoon: true,
  },
  {
    slug: "heic-to-png",
    title: "HEIC to PNG",
    description: "Convert iPhone HEIC photos to PNG format.",
    icon: ArrowRightLeft,
    emoji: "📱",
    category: "convert",
    acceptedTypes: ".heic,.heif",
    comingSoon: true,
  },
  {
    slug: "tiff-to-jpg",
    title: "TIFF to JPG",
    description: "Convert TIFF images to JPG format.",
    icon: ArrowRightLeft,
    emoji: "🖨️",
    category: "convert",
    acceptedTypes: ".tif,.tiff",
    comingSoon: true,
  },
  {
    slug: "tiff-to-png",
    title: "TIFF to PNG",
    description: "Convert TIFF images to PNG format.",
    icon: ArrowRightLeft,
    emoji: "🖨️",
    category: "convert",
    acceptedTypes: ".tif,.tiff",
    comingSoon: true,
  },
  {
    slug: "psd-to-jpg",
    title: "PSD to JPG",
    description: "Convert Photoshop PSD files to JPG images.",
    icon: ImageDown,
    emoji: "🎨",
    category: "convert",
    acceptedTypes: ".psd",
    comingSoon: true,
  },
  {
    slug: "psd-to-png",
    title: "PSD to PNG",
    description: "Convert Photoshop PSD files to PNG images.",
    icon: ImageDown,
    emoji: "🎨",
    category: "convert",
    acceptedTypes: ".psd",
    comingSoon: true,
  },
  {
    slug: "eps-to-jpg",
    title: "EPS to JPG",
    description: "Convert EPS vector files to JPG images.",
    icon: FileImage,
    emoji: "📐",
    category: "convert",
    acceptedTypes: ".eps",
    comingSoon: true,
  },
  {
    slug: "eps-to-png",
    title: "EPS to PNG",
    description: "Convert EPS vector files to PNG images.",
    icon: FileImage,
    emoji: "📐",
    category: "convert",
    acceptedTypes: ".eps",
    comingSoon: true,
  },
  {
    slug: "eps-to-svg",
    title: "EPS to SVG",
    description: "Convert EPS files to SVG vector format.",
    icon: FileImage,
    emoji: "📐",
    category: "convert",
    acceptedTypes: ".eps",
    comingSoon: true,
  },
  {
    slug: "png-to-svg",
    title: "PNG to SVG",
    description: "Vectorize PNG images to SVG format.",
    icon: ImagePlus,
    emoji: "✨",
    category: "convert",
    acceptedTypes: ".png",
    comingSoon: true,
  },
  {
    slug: "jpg-to-svg",
    title: "JPG to SVG",
    description: "Vectorize JPG images to SVG format.",
    icon: ImagePlus,
    emoji: "✨",
    category: "convert",
    acceptedTypes: ".jpg,.jpeg",
    comingSoon: true,
  },
  {
    slug: "gif-to-mp4",
    title: "GIF to MP4",
    description: "Convert animated GIFs to MP4 video.",
    icon: Film,
    emoji: "🎬",
    category: "convert",
    acceptedTypes: ".gif",
    comingSoon: true,
  },
  {
    slug: "image-to-text",
    title: "Image to Text (OCR)",
    description: "Extract text from images using optical character recognition.",
    icon: ScanSearch,
    emoji: "👁️",
    category: "convert",
    acceptedTypes: IMG_RASTER,
    comingSoon: true,
  },

  // ── AI (서버 필요 — 서버 추가 시 comingSoon 해제 후 활성화) ──
  // category 타입에 "ai" 추가, categoryColors/categories 배열에도 ai 엔트리 추가 필요
  // import { Eraser, EyeOff, UserMinus, RemoveFormatting, Paintbrush, ZoomIn, PaintBucket, Wand2, Eye, CircleDot } from "lucide-react";
  //
  // { slug: "remove-background", title: "Remove Background", description: "Automatically detect and remove image backgrounds.", icon: Eraser, emoji: "✨", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "transparent-background", title: "Transparent Background", description: "Make image backgrounds transparent.", icon: EyeOff, emoji: "🔍", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "blur-background", title: "Blur Background", description: "Automatically blur the background while keeping the subject sharp.", icon: Blend, emoji: "🌫️", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "remove-watermark", title: "Remove Watermark", description: "Intelligently remove watermarks from images.", icon: Eraser, emoji: "🧹", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "remove-objects", title: "Remove Objects", description: "Erase unwanted objects from photos with AI.", icon: Eraser, emoji: "🗑️", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "remove-person", title: "Remove Person", description: "Remove people from photos automatically.", icon: UserMinus, emoji: "👻", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "remove-text", title: "Remove Text", description: "Erase text from images using AI.", icon: RemoveFormatting, emoji: "🔤", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "cleanup-picture", title: "Cleanup Picture", description: "Automatically clean up and enhance photos.", icon: Paintbrush, emoji: "🧽", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "unblur", title: "Unblur Image", description: "Enhance and sharpen blurry images with AI.", icon: Eye, emoji: "👁️", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "upscale", title: "Upscale Image", description: "Enlarge images while maintaining quality using AI.", icon: ZoomIn, emoji: "🔍", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "colorize", title: "Colorize Photo", description: "Add color to black and white photos with AI.", icon: PaintBucket, emoji: "🎨", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
  // { slug: "ai-image-generator", title: "AI Image Generator", description: "Generate images from text descriptions.", icon: Wand2, emoji: "🪄", category: "ai", acceptedTypes: "", comingSoon: true },
  // { slug: "blur-face", title: "Blur Face", description: "Automatically detect and blur faces in images.", icon: CircleDot, emoji: "😶‍🌫️", category: "ai", acceptedTypes: IMG_RASTER, comingSoon: true },
];

export type ImageCategory = ImageToolDefinition["category"];

export const categoryColors: Record<ImageCategory, { bg: string; text: string; bgHover: string; textHover: string }> = {
  edit:     { bg: "bg-amber-50 dark:bg-amber-950/40",   text: "text-amber-600 dark:text-amber-400",   bgHover: "group-hover:bg-amber-500",   textHover: "group-hover:text-white" },
  convert:  { bg: "bg-blue-50 dark:bg-blue-950/40",     text: "text-blue-600 dark:text-blue-400",     bgHover: "group-hover:bg-blue-500",    textHover: "group-hover:text-white" },
  effects:  { bg: "bg-purple-50 dark:bg-purple-950/40", text: "text-purple-600 dark:text-purple-400", bgHover: "group-hover:bg-purple-500",  textHover: "group-hover:text-white" },
  compose:  { bg: "bg-cyan-50 dark:bg-cyan-950/40",     text: "text-cyan-600 dark:text-cyan-400",     bgHover: "group-hover:bg-cyan-500",    textHover: "group-hover:text-white" },
  optimize: { bg: "bg-green-50 dark:bg-green-950/40",   text: "text-green-600 dark:text-green-400",   bgHover: "group-hover:bg-green-500",   textHover: "group-hover:text-white" },
  generate: { bg: "bg-rose-50 dark:bg-rose-950/40",     text: "text-rose-600 dark:text-rose-400",     bgHover: "group-hover:bg-rose-500",    textHover: "group-hover:text-white" },
};

export const categories = [
  { key: "edit" as const, label: "Edit", emoji: "✏️" },
  { key: "convert" as const, label: "Convert", emoji: "🔄" },
  { key: "effects" as const, label: "Effects", emoji: "✨" },
  { key: "compose" as const, label: "Compose", emoji: "🧩" },
  { key: "optimize" as const, label: "Optimize", emoji: "⚡" },
  { key: "generate" as const, label: "Generate", emoji: "🎨" },
];

const toolsBySlug = new Map(tools.map((t) => [t.slug, t]));

export function getToolBySlug(slug: string) {
  return toolsBySlug.get(slug);
}
