import {
  Merge,
  Scissors,
  Trash2,
  FileOutput,
  GripVertical,
  ScanLine,
  FileDown,
  FileImage,
  ImageDown,
  FileSpreadsheet,
  Presentation,
  Image,
  FileText,
  FileCheck,
  FileUp,
  ImageUp,
  FileInput,
  Globe,
  ImagePlus,
  Images,
  Smartphone,
  FileType2,
  PenLine,
  RotateCw,
  Hash,
  Droplets,
  Crop,
  PenTool,
  Highlighter,
  Layers,
  Maximize2,
  Tags,
  Palette,
  Minimize2,
  Wrench,
  ScanSearch,
  Zap,
  Lock,
  LockOpen,
  EyeOff,
  Languages,
  BookOpen,
  Shield,
  FilePlus,
  Heading,
  Combine,
  type LucideIcon,
} from "lucide-react";

export interface ToolDefinition {
  slug: string;
  title: string;
  description: string;
  icon: LucideIcon;
  emoji: string;
  category: "organize" | "convert" | "edit" | "optimize" | "security";
  acceptedTypes: string;
  comingSoon?: boolean;
}

export const tools: ToolDefinition[] = [
  // ── Organize ──────────────────────────────────────────
  {
    slug: "merge",
    title: "Merge PDF",
    description: "Combine multiple PDF files into one document.",
    icon: Merge,
    emoji: "🔗",
    category: "organize",
    acceptedTypes: ".pdf",
  },
  {
    slug: "split",
    title: "Split PDF",
    description: "Separate a PDF into individual pages or sections.",
    icon: Scissors,
    emoji: "✂️",
    category: "organize",
    acceptedTypes: ".pdf",
  },

  // ── Convert ───────────────────────────────────────────
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert PDF pages to high-quality JPG images.",
    icon: FileImage,
    emoji: "🖼️",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "extract-images",
    title: "Extract Images",
    description: "Extract all embedded images from a PDF document.",
    icon: ImageDown,
    emoji: "📸",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "pdf-to-png",
    title: "PDF to PNG",
    description: "Convert PDF pages to high-quality PNG images.",
    icon: Image,
    emoji: "🎨",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "pdf-to-text",
    title: "PDF to Text",
    description: "Extract all text content from PDF documents.",
    icon: FileText,
    emoji: "📄",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert JPG images into a PDF document.",
    icon: ImageUp,
    emoji: "📷",
    category: "convert",
    acceptedTypes: ".jpg,.jpeg",
  },
  {
    slug: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert web pages and HTML files to PDF.",
    icon: Globe,
    emoji: "🌐",
    category: "convert",
    acceptedTypes: ".html,.htm",
  },
  {
    slug: "png-to-pdf",
    title: "PNG to PDF",
    description: "Convert PNG images into a PDF document.",
    icon: ImagePlus,
    emoji: "🖌️",
    category: "convert",
    acceptedTypes: ".png",
  },
  {
    slug: "image-to-pdf",
    title: "Image to PDF",
    description: "Combine multiple images of any format into a single PDF.",
    icon: Images,
    emoji: "🏞️",
    category: "convert",
    acceptedTypes: ".jpg,.jpeg,.png,.gif,.webp,.svg,.avif,.bmp,.ico,.heic,.heif,.tif,.tiff",
  },
  {
    slug: "webp-to-pdf",
    title: "WEBP to PDF",
    description: "Convert WEBP images into a PDF document.",
    icon: Image,
    emoji: "🖼️",
    category: "convert",
    acceptedTypes: ".webp",
  },
  {
    slug: "tiff-to-pdf",
    title: "TIFF to PDF",
    description: "Convert TIFF images into a PDF document.",
    icon: FileType2,
    emoji: "🖨️",
    category: "convert",
    acceptedTypes: ".tif,.tiff",
  },
  {
    slug: "heic-to-pdf",
    title: "HEIC to PDF",
    description: "Convert iPhone HEIC photos into a PDF document.",
    icon: Smartphone,
    emoji: "📱",
    category: "convert",
    acceptedTypes: ".heic,.heif",
  },

  // ── Organize ───────────────────────────────────────────
  {
    slug: "delete-pages",
    title: "Delete Pages",
    description: "Remove specific pages from a PDF document.",
    icon: Trash2,
    emoji: "🗑️",
    category: "organize",
    acceptedTypes: ".pdf",
  },
  {
    slug: "extract-pages",
    title: "Extract Pages",
    description: "Extract selected pages into a new PDF file.",
    icon: FileOutput,
    emoji: "📤",
    category: "organize",
    acceptedTypes: ".pdf",
  },
  {
    slug: "organize-pages",
    title: "Organize Pages",
    description: "Reorder, add, or remove pages visually.",
    icon: GripVertical,
    emoji: "📋",
    category: "organize",
    acceptedTypes: ".pdf",
  },
  {
    slug: "scan-to-pdf",
    title: "Scan to PDF",
    description: "Capture scans from your device and convert to PDF.",
    icon: ScanLine,
    emoji: "📸",
    category: "organize",
    acceptedTypes: ".jpg,.jpeg,.png",
  },

  // ── Edit ──────────────────────────────────────────────
  {
    slug: "edit-pdf",
    title: "Edit PDF",
    description: "Add text, images, shapes, and annotations to a PDF.",
    icon: PenLine,
    emoji: "✏️",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "rotate",
    title: "Rotate PDF",
    description: "Rotate PDF pages to the correct orientation.",
    icon: RotateCw,
    emoji: "🔄",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "page-numbers",
    title: "Page Numbers",
    description: "Add page numbers to your PDF document.",
    icon: Hash,
    emoji: "🔢",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "watermark",
    title: "Watermark",
    description: "Add text or image watermarks to your PDF.",
    icon: Droplets,
    emoji: "💧",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "crop",
    title: "Crop PDF",
    description: "Crop margins or select specific areas of PDF pages.",
    icon: Crop,
    emoji: "🔲",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "sign",
    title: "Sign PDF",
    description: "Add electronic signatures to your PDF documents.",
    icon: PenTool,
    emoji: "🖋️",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "annotate",
    title: "Annotate PDF",
    description: "Highlight, underline, and add comments to PDFs.",
    icon: Highlighter,
    emoji: "💬",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "flatten",
    title: "Flatten PDF",
    description: "Merge form fields and annotations into the page content.",
    icon: Layers,
    emoji: "📐",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "resize",
    title: "Resize PDF",
    description: "Change PDF page size (A4, Letter, custom).",
    icon: Maximize2,
    emoji: "📏",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "edit-metadata",
    title: "Edit Metadata",
    description: "Change PDF title, author, keywords, and other metadata.",
    icon: Tags,
    emoji: "🏷️",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "pages-per-sheet",
    title: "Pages Per Sheet",
    description: "Arrange multiple PDF pages on a single sheet for efficient printing.",
    icon: Presentation,
    emoji: "📄",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "header-footer",
    title: "Header & Footer",
    description: "Add repeating headers and footers to every page of your PDF.",
    icon: Heading,
    emoji: "📝",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "grayscale",
    title: "Grayscale",
    description: "Convert PDF colors to black and white.",
    icon: Palette,
    emoji: "⬛",
    category: "edit",
    acceptedTypes: ".pdf",
  },

  {
    slug: "booklet",
    title: "Booklet",
    description: "Rearrange pages for saddle-stitch booklet printing.",
    icon: BookOpen,
    emoji: "📖",
    category: "edit",
    acceptedTypes: ".pdf",
  },
  {
    slug: "overlay",
    title: "PDF Overlay",
    description: "Merge two PDFs as layers — add letterheads, stamps, or backgrounds.",
    icon: Combine,
    emoji: "📑",
    category: "edit",
    acceptedTypes: ".pdf",
  },

  // ── Optimize ──────────────────────────────────────────
  {
    slug: "web-optimize",
    title: "Web Optimize",
    description: "Linearize PDFs for faster web loading.",
    icon: Zap,
    emoji: "🚀",
    category: "optimize",
    acceptedTypes: ".pdf",
  },

  // ── Security ──────────────────────────────────────────
  {
    slug: "protect",
    title: "Protect PDF",
    description: "Add password protection and encrypt your PDF.",
    icon: Lock,
    emoji: "🔒",
    category: "security",
    acceptedTypes: ".pdf",
  },
  {
    slug: "redact",
    title: "Redact PDF",
    description: "Permanently remove sensitive information from PDFs.",
    icon: EyeOff,
    emoji: "🙈",
    category: "security",
    acceptedTypes: ".pdf",
  },
  // ── Coming Soon (server required) ─────────────────────
  {
    slug: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    description: "Convert to PDF/A format for long-term archiving.",
    icon: FileCheck,
    emoji: "🗃️",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "compress",
    title: "Compress PDF",
    description: "Reduce PDF file size without losing quality.",
    icon: Minimize2,
    emoji: "📦",
    category: "optimize",
    acceptedTypes: ".pdf",
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF documents to editable Word files.",
    icon: FileDown,
    emoji: "📝",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract tables and data from PDFs into Excel spreadsheets.",
    icon: FileSpreadsheet,
    emoji: "📊",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "pdf-to-ppt",
    title: "PDF to PPT",
    description: "Convert PDF files to editable PowerPoint slides.",
    icon: Presentation,
    emoji: "📽️",
    category: "convert",
    acceptedTypes: ".pdf",
  },
  {
    slug: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert Word documents to PDF format.",
    icon: FileUp,
    emoji: "✍️",
    category: "convert",
    acceptedTypes: ".doc,.docx",
  },
  {
    slug: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF format.",
    icon: FileInput,
    emoji: "📈",
    category: "convert",
    acceptedTypes: ".xls,.xlsx",
  },
  {
    slug: "ppt-to-pdf",
    title: "PPT to PDF",
    description: "Convert PowerPoint presentations to PDF format.",
    icon: FilePlus,
    emoji: "🎞️",
    category: "convert",
    acceptedTypes: ".ppt,.pptx",
  },
  {
    slug: "repair",
    title: "Repair PDF",
    description: "Fix damaged or corrupted PDF files.",
    icon: Wrench,
    emoji: "🔧",
    category: "optimize",
    acceptedTypes: ".pdf",
  },
  {
    slug: "ocr",
    title: "OCR PDF",
    description: "Make scanned PDFs searchable with text recognition.",
    icon: ScanSearch,
    emoji: "👁️",
    category: "optimize",
    acceptedTypes: ".pdf",
  },
  {
    slug: "unlock",
    title: "Unlock PDF",
    description: "Remove password protection from PDF files.",
    icon: LockOpen,
    emoji: "🔓",
    category: "security",
    acceptedTypes: ".pdf",
  },
  {
    slug: "translate",
    title: "Translate PDF",
    description: "Translate PDF content to another language with AI.",
    icon: Languages,
    emoji: "🌍",
    category: "security",
    acceptedTypes: ".pdf",
    comingSoon: true,
  },
];

export const categoryColors: Record<ToolDefinition["category"], { bg: string; text: string; bgHover: string; textHover: string }> = {
  organize: { bg: "bg-amber-50 dark:bg-amber-950/40", text: "text-amber-600 dark:text-amber-400", bgHover: "group-hover:bg-amber-500", textHover: "group-hover:text-white" },
  convert:  { bg: "bg-blue-50 dark:bg-blue-950/40",  text: "text-blue-600 dark:text-blue-400",  bgHover: "group-hover:bg-blue-500",  textHover: "group-hover:text-white" },
  edit:     { bg: "bg-purple-50 dark:bg-purple-950/40", text: "text-purple-600 dark:text-purple-400", bgHover: "group-hover:bg-purple-500", textHover: "group-hover:text-white" },
  optimize: { bg: "bg-green-50 dark:bg-green-950/40",  text: "text-green-600 dark:text-green-400",  bgHover: "group-hover:bg-green-500",  textHover: "group-hover:text-white" },
  security: { bg: "bg-zinc-100 dark:bg-zinc-800/40",  text: "text-zinc-600 dark:text-zinc-400",  bgHover: "group-hover:bg-zinc-600",  textHover: "group-hover:text-white" },
};

export const categories = [
  { key: "organize" as const, label: "Organize", emoji: "📂" },
  { key: "convert" as const, label: "Convert", emoji: "🔄" },
  { key: "edit" as const, label: "Edit", emoji: "✏️" },
  { key: "optimize" as const, label: "Optimize", emoji: "⚡" },
  { key: "security" as const, label: "Security", emoji: "🛡️" },
];

const toolsBySlug = new Map(tools.map((t) => [t.slug, t]));

export function getToolBySlug(slug: string) {
  return toolsBySlug.get(slug);
}
