import {
  LetterText,
  CaseSensitive,
  BarChart3,
  Target,
  Copy,
  ArrowUpDown,
  Undo2,
  Repeat,
  ArrowDownAZ,
  ListX,
  ListOrdered,
  TextCursorInput,
  Merge,
  Split,
  WrapText,
  Space,
  RemoveFormatting,
  Eraser,
  SmilePlus,
  Code,
  Languages,
  Scissors,
  Replace,
  GitCompareArrows,
  Regex,
  Mail,
  Link,
  Hash,
  Filter,
  FileKey,
  Globe,
  FileCode,
  Binary,
  ShieldCheck,
  HexagonIcon,
  RotateCw,
  TextQuote,
  KeyRound,
  Shuffle,
  Fingerprint,
  Lock,
  Braces,
  type LucideIcon,
} from "lucide-react";

export interface TextToolDefinition {
  slug: string;
  title: string;
  description: string;
  icon: LucideIcon;
  emoji: string;
  category: "count" | "transform" | "clean" | "find" | "encode" | "generate";
  hasFileOutput?: boolean;
  dualInput?: boolean;
  noInput?: boolean;
}

export const tools: TextToolDefinition[] = [
  // ── Count ──────────────────────────────────────────────
  {
    slug: "word-counter",
    title: "Word Counter",
    description: "Count words, sentences, and paragraphs in your text.",
    icon: LetterText,
    emoji: "🔢",
    category: "count",
  },
  {
    slug: "character-counter",
    title: "Character Counter",
    description: "Count characters with and without spaces.",
    icon: CaseSensitive,
    emoji: "🔤",
    category: "count",
  },
  {
    slug: "text-statistics",
    title: "Text Statistics",
    description: "Analyze readability, reading time, and text complexity.",
    icon: BarChart3,
    emoji: "📊",
    category: "count",
  },
  {
    slug: "keyword-density",
    title: "Keyword Density",
    description: "Analyze word frequency and keyword density for SEO.",
    icon: Target,
    emoji: "🎯",
    category: "count",
  },
  {
    slug: "find-duplicates",
    title: "Find Duplicates",
    description: "Detect duplicate lines or words in your text.",
    icon: Copy,
    emoji: "👯",
    category: "count",
  },

  // ── Transform ──────────────────────────────────────────
  {
    slug: "case-converter",
    title: "Case Converter",
    description: "Convert text between uppercase, lowercase, title case, and more.",
    icon: ArrowUpDown,
    emoji: "🔠",
    category: "transform",
  },
  {
    slug: "reverse-text",
    title: "Reverse Text",
    description: "Reverse characters, words, or lines in your text.",
    icon: Undo2,
    emoji: "🔙",
    category: "transform",
  },
  {
    slug: "text-repeater",
    title: "Text Repeater",
    description: "Repeat text or characters a specified number of times.",
    icon: Repeat,
    emoji: "🔁",
    category: "transform",
  },
  {
    slug: "text-sort",
    title: "Sort Lines",
    description: "Sort lines alphabetically, numerically, or by length.",
    icon: ArrowDownAZ,
    emoji: "📋",
    category: "transform",
  },
  {
    slug: "remove-duplicates",
    title: "Remove Duplicate Lines",
    description: "Remove duplicate lines while preserving order.",
    icon: ListX,
    emoji: "🗑️",
    category: "transform",
  },
  {
    slug: "add-line-numbers",
    title: "Add Line Numbers",
    description: "Prefix each line with its line number.",
    icon: ListOrdered,
    emoji: "🔢",
    category: "transform",
  },
  {
    slug: "add-prefix-suffix",
    title: "Add Prefix / Suffix",
    description: "Add text before or after every line.",
    icon: TextCursorInput,
    emoji: "➕",
    category: "transform",
  },
  {
    slug: "join-text",
    title: "Join Lines",
    description: "Merge multiple lines into one with a custom delimiter.",
    icon: Merge,
    emoji: "🔗",
    category: "transform",
  },
  {
    slug: "split-text",
    title: "Split Text",
    description: "Split text into lines by a delimiter or character count.",
    icon: Split,
    emoji: "✂️",
    category: "transform",
  },

  // ── Clean ──────────────────────────────────────────────
  {
    slug: "remove-line-breaks",
    title: "Remove Line Breaks",
    description: "Remove all line breaks and join text into a single line.",
    icon: WrapText,
    emoji: "📄",
    category: "clean",
  },
  {
    slug: "remove-extra-spaces",
    title: "Remove Extra Spaces",
    description: "Collapse multiple spaces into a single space.",
    icon: Space,
    emoji: "⬜",
    category: "clean",
  },
  {
    slug: "remove-empty-lines",
    title: "Remove Empty Lines",
    description: "Strip blank lines from your text.",
    icon: RemoveFormatting,
    emoji: "🧹",
    category: "clean",
  },
  {
    slug: "remove-special-characters",
    title: "Remove Special Characters",
    description: "Strip punctuation and special characters from text.",
    icon: Eraser,
    emoji: "🚫",
    category: "clean",
  },
  {
    slug: "remove-emojis",
    title: "Remove Emojis",
    description: "Strip all emoji characters from your text.",
    icon: SmilePlus,
    emoji: "😶",
    category: "clean",
  },
  {
    slug: "remove-html-tags",
    title: "Remove HTML Tags",
    description: "Strip all HTML tags and extract plain text.",
    icon: Code,
    emoji: "🏷️",
    category: "clean",
  },
  {
    slug: "remove-accents",
    title: "Remove Accents",
    description: "Replace accented characters with their plain equivalents.",
    icon: Languages,
    emoji: "àA",
    category: "clean",
  },
  {
    slug: "trim-text",
    title: "Trim Text",
    description: "Remove leading and trailing whitespace from each line.",
    icon: Scissors,
    emoji: "✂️",
    category: "clean",
  },

  // ── Find ───────────────────────────────────────────────
  {
    slug: "find-and-replace",
    title: "Find & Replace",
    description: "Search and replace text with support for regex patterns.",
    icon: Replace,
    emoji: "🔍",
    category: "find",
  },
  {
    slug: "text-diff",
    title: "Text Diff",
    description: "Compare two texts side by side and highlight differences.",
    icon: GitCompareArrows,
    emoji: "📑",
    category: "find",
    dualInput: true,
  },
  {
    slug: "regex-tester",
    title: "Regex Tester",
    description: "Test regular expressions with live matching and capture groups.",
    icon: Regex,
    emoji: "🧪",
    category: "find",
  },
  {
    slug: "email-extractor",
    title: "Email Extractor",
    description: "Extract all email addresses from your text.",
    icon: Mail,
    emoji: "📧",
    category: "find",
  },
  {
    slug: "url-extractor",
    title: "URL Extractor",
    description: "Extract all URLs and links from your text.",
    icon: Link,
    emoji: "🔗",
    category: "find",
  },
  {
    slug: "number-extractor",
    title: "Number Extractor",
    description: "Extract all numbers from your text.",
    icon: Hash,
    emoji: "#️⃣",
    category: "find",
  },
  {
    slug: "filter-lines",
    title: "Filter Lines",
    description: "Keep or remove lines matching a pattern.",
    icon: Filter,
    emoji: "🔎",
    category: "find",
  },

  // ── Encode ─────────────────────────────────────────────
  {
    slug: "base64",
    title: "Base64 Encode / Decode",
    description: "Encode text to Base64 or decode Base64 back to text.",
    icon: FileKey,
    emoji: "🔐",
    category: "encode",
  },
  {
    slug: "url-encode",
    title: "URL Encode / Decode",
    description: "Percent-encode or decode text for use in URLs.",
    icon: Globe,
    emoji: "🌐",
    category: "encode",
  },
  {
    slug: "html-encode",
    title: "HTML Encode / Decode",
    description: "Escape or unescape HTML entities in text.",
    icon: FileCode,
    emoji: "🏷️",
    category: "encode",
  },
  {
    slug: "unicode-escape",
    title: "Unicode Escape / Unescape",
    description: "Convert text to Unicode escape sequences and back.",
    icon: Languages,
    emoji: "🔣",
    category: "encode",
  },
  {
    slug: "morse-code",
    title: "Morse Code",
    description: "Translate text to Morse code and vice versa.",
    icon: ShieldCheck,
    emoji: "📡",
    category: "encode",
  },
  {
    slug: "binary-converter",
    title: "Binary Converter",
    description: "Convert text to binary representation and back.",
    icon: Binary,
    emoji: "💻",
    category: "encode",
  },
  {
    slug: "hex-converter",
    title: "Hex Converter",
    description: "Convert text to hexadecimal encoding and back.",
    icon: HexagonIcon,
    emoji: "🔢",
    category: "encode",
  },
  {
    slug: "rot13",
    title: "ROT13 Cipher",
    description: "Apply ROT13 letter substitution cipher to text.",
    icon: RotateCw,
    emoji: "🔄",
    category: "encode",
  },

  // ── Generate ───────────────────────────────────────────
  {
    slug: "lorem-ipsum",
    title: "Lorem Ipsum Generator",
    description: "Generate placeholder text in paragraphs, sentences, or words.",
    icon: TextQuote,
    emoji: "📜",
    category: "generate",
    noInput: true,
  },
  {
    slug: "slug-generator",
    title: "Slug Generator",
    description: "Convert text into URL-friendly slugs.",
    icon: Link,
    emoji: "🔗",
    category: "generate",
  },
  {
    slug: "password-generator",
    title: "Password Generator",
    description: "Generate strong, random passwords with custom rules.",
    icon: KeyRound,
    emoji: "🔑",
    category: "generate",
    noInput: true,
  },
  {
    slug: "random-string",
    title: "Random String Generator",
    description: "Generate random strings of specified length and character set.",
    icon: Shuffle,
    emoji: "🎲",
    category: "generate",
    noInput: true,
  },
  {
    slug: "uuid-generator",
    title: "UUID Generator",
    description: "Generate universally unique identifiers (UUIDs).",
    icon: Fingerprint,
    emoji: "🆔",
    category: "generate",
    noInput: true,
  },
  {
    slug: "hash-generator",
    title: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and other hash digests.",
    icon: Lock,
    emoji: "🔒",
    category: "generate",
  },
  {
    slug: "json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and minify JSON with syntax highlighting.",
    icon: Braces,
    emoji: "📋",
    category: "generate",
  },
];

export type TextCategory = TextToolDefinition["category"];

export const categoryColors: Record<TextCategory, { bg: string; text: string; bgHover: string; textHover: string }> = {
  count:     { bg: "bg-amber-50 dark:bg-amber-950/40",   text: "text-amber-600 dark:text-amber-400",   bgHover: "group-hover:bg-amber-500",   textHover: "group-hover:text-white" },
  transform: { bg: "bg-blue-50 dark:bg-blue-950/40",     text: "text-blue-600 dark:text-blue-400",     bgHover: "group-hover:bg-blue-500",    textHover: "group-hover:text-white" },
  clean:     { bg: "bg-emerald-50 dark:bg-emerald-950/40", text: "text-emerald-600 dark:text-emerald-400", bgHover: "group-hover:bg-emerald-500", textHover: "group-hover:text-white" },
  find:      { bg: "bg-purple-50 dark:bg-purple-950/40", text: "text-purple-600 dark:text-purple-400", bgHover: "group-hover:bg-purple-500",  textHover: "group-hover:text-white" },
  encode:    { bg: "bg-cyan-50 dark:bg-cyan-950/40",     text: "text-cyan-600 dark:text-cyan-400",     bgHover: "group-hover:bg-cyan-500",    textHover: "group-hover:text-white" },
  generate:  { bg: "bg-rose-50 dark:bg-rose-950/40",     text: "text-rose-600 dark:text-rose-400",     bgHover: "group-hover:bg-rose-500",    textHover: "group-hover:text-white" },
};

export const categories = [
  { key: "count" as const, label: "Count", emoji: "🔢" },
  { key: "transform" as const, label: "Transform", emoji: "🔄" },
  { key: "clean" as const, label: "Clean", emoji: "🧹" },
  { key: "find" as const, label: "Find", emoji: "🔍" },
  { key: "encode" as const, label: "Encode", emoji: "🔐" },
  { key: "generate" as const, label: "Generate", emoji: "⚡" },
];

const toolsBySlug = new Map(tools.map((t) => [t.slug, t]));

export function getToolBySlug(slug: string) {
  return toolsBySlug.get(slug);
}
