import { describe, it, expect, vi, beforeEach } from "vitest";
import { PDFDocument } from "pdf-lib";
import annotatePdf from "../annotate-pdf";
import type {
  AnnotateElement,
  HighlightElement,
  UnderlineElement,
  StrikethroughElement,
  RectangleElement,
  EllipseElement,
  ArrowElement,
  FreehandElement,
  TextBoxElement,
  StampElement,
} from "../../../../app/[locale]/pdf/(tools)/_components/annotate-pdf/annotate-types";
import {
  createMarkedPdf,
  resultToPdf,
  createProgressTracker,
} from "./helpers";

// ─── Canvas Mock ──────────────────────────────────────────────
// The processor uses document.createElement("canvas") for sticky notes,
// stamps, and CJK text rendering. We mock it to return a minimal 1x1 PNG.

// Valid 1x1 RGB PNG (generated by Python zlib)
const TINY_PNG = new Uint8Array([
  0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00,0x00,0x00,0x0d,0x49,0x48,
  0x44,0x52,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,0x08,0x02,0x00,0x00,
  0x00,0x90,0x77,0x53,0xde,0x00,0x00,0x00,0x0c,0x49,0x44,0x41,0x54,0x78,
  0x9c,0x63,0xf8,0xcf,0xc0,0x00,0x00,0x03,0x01,0x01,0x00,0xc9,0xfe,0x92,
  0xef,0x00,0x00,0x00,0x00,0x49,0x45,0x4e,0x44,0xae,0x42,0x60,0x82,
]);

function createMockCanvas() {
  const mockCtx = {
    scale: vi.fn(),
    clearRect: vi.fn(),
    fillRect: vi.fn(),
    strokeRect: vi.fn(),
    fillText: vi.fn(),
    beginPath: vi.fn(),
    moveTo: vi.fn(),
    lineTo: vi.fn(),
    closePath: vi.fn(),
    fill: vi.fn(),
    stroke: vi.fn(),
    translate: vi.fn(),
    measureText: vi.fn(() => ({ width: 50 })),
    font: "",
    fillStyle: "",
    strokeStyle: "",
    lineWidth: 1,
    textAlign: "left",
    textBaseline: "top",
  };

  const mockCanvas = {
    width: 0,
    height: 0,
    getContext: vi.fn(() => mockCtx),
    toBlob: vi.fn((cb: (b: Blob) => void) => {
      cb(new Blob([TINY_PNG], { type: "image/png" }));
    }),
  };

  return mockCanvas;
}

beforeEach(() => {
  // Mock document.createElement for canvas (Node has no DOM)
  const mockDoc = {
    createElement: vi.fn((tag: string) => {
      if (tag === "canvas") {
        return createMockCanvas() as unknown as HTMLCanvasElement;
      }
      return {} as HTMLElement;
    }),
  };
  if (typeof globalThis.document === "undefined") {
    (globalThis as Record<string, unknown>).document = mockDoc;
  } else {
    vi.spyOn(document, "createElement").mockImplementation(mockDoc.createElement);
  }
});

// ─── 헬퍼: 어노테이션 팩토리 ──────────────────────────────────

let _counter = 0;
function baseProps(
  type: string,
  pageIndex = 0,
  overrides: Partial<AnnotateElement> = {},
) {
  return {
    id: `test_${++_counter}`,
    type,
    pageIndex,
    x: 50,
    y: 100,
    width: 200,
    height: 30,
    rotation: 0,
    opacity: 1,
    ...overrides,
  };
}

function makeHighlight(overrides: Partial<HighlightElement> = {}): HighlightElement {
  return {
    ...baseProps("highlight"),
    color: "yellow",
    ...overrides,
  } as HighlightElement;
}

function makeUnderline(overrides: Partial<UnderlineElement> = {}): UnderlineElement {
  return {
    ...baseProps("underline"),
    color: "#FF0000",
    strokeWidth: 2,
    ...overrides,
  } as UnderlineElement;
}

function makeStrikethrough(overrides: Partial<StrikethroughElement> = {}): StrikethroughElement {
  return {
    ...baseProps("strikethrough"),
    color: "#FF0000",
    strokeWidth: 2,
    ...overrides,
  } as StrikethroughElement;
}

function makeRectangle(overrides: Partial<RectangleElement> = {}): RectangleElement {
  return {
    ...baseProps("rectangle"),
    borderColor: "#000000",
    fillColor: "#FF000080",
    strokeWidth: 2,
    ...overrides,
  } as RectangleElement;
}

function makeEllipse(overrides: Partial<EllipseElement> = {}): EllipseElement {
  return {
    ...baseProps("ellipse"),
    width: 100,
    height: 80,
    borderColor: "#0000FF",
    fillColor: "transparent",
    strokeWidth: 2,
    ...overrides,
  } as EllipseElement;
}

function makeArrow(overrides: Partial<ArrowElement> = {}): ArrowElement {
  return {
    ...baseProps("arrow"),
    points: [50, 100, 250, 200] as [number, number, number, number],
    strokeColor: "#000000",
    strokeWidth: 2,
    headSize: 15,
    ...overrides,
  } as ArrowElement;
}

function makeFreehand(overrides: Partial<FreehandElement> = {}): FreehandElement {
  return {
    ...baseProps("freehand"),
    points: [10, 20, 30, 40, 50, 60, 70, 80],
    strokeColor: "#FF0000",
    strokeWidth: 3,
    ...overrides,
  } as FreehandElement;
}

function makeTextBox(overrides: Partial<TextBoxElement> = {}): TextBoxElement {
  return {
    ...baseProps("text-box"),
    width: 200,
    height: 50,
    content: "Hello World",
    fontFamily: "Helvetica",
    fontSize: 16,
    fontColor: "#000000",
    backgroundColor: "transparent",
    borderColor: "transparent",
    bold: false,
    italic: false,
    align: "left" as const,
    lineHeight: 1.2,
    ...overrides,
  } as TextBoxElement;
}

function makeStamp(overrides: Partial<StampElement> = {}): StampElement {
  return {
    ...baseProps("stamp"),
    width: 150,
    height: 50,
    stampKind: "approved" as const,
    color: "#22C55E",
    ...overrides,
  } as StampElement;
}

/** Compare byte length of result to original — annotations should add content */
async function getOriginalByteLength(file: File): Promise<number> {
  const origPdf = await PDFDocument.load(await file.arrayBuffer());
  const origBytes = await origPdf.save();
  return origBytes.length;
}

// ═══════════════════════════════════════════════════════════════
// 테스트
// ═══════════════════════════════════════════════════════════════

describe("annotate-pdf — 빈 어노테이션", () => {
  it("어노테이션이 없으면 원본 PDF를 그대로 반환한다", async () => {
    const file = await createMarkedPdf(2);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf([file], { annotations: [] }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(2);
    expect(result.blob.type).toBe("application/pdf");
  });

  it("annotations 옵션이 없어도 에러 없이 처리한다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf([file], {}, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 하이라이트", () => {
  it("하이라이트 어노테이션이 적용되면 PDF 바이트가 증가한다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("하이라이트 opacity 기본값은 0.35이다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // opacity를 명시하지 않으면 processor가 0.35 사용
    const hl = makeHighlight({ opacity: undefined as unknown as number });
    const result = await annotatePdf(
      [file],
      { annotations: [hl] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("다양한 하이라이트 색상이 모두 적용된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const annotations = [
      makeHighlight({ color: "yellow", y: 50 }),
      makeHighlight({ color: "green", y: 100 }),
      makeHighlight({ color: "pink", y: 150 }),
      makeHighlight({ color: "blue", y: 200 }),
      makeHighlight({ color: "orange", y: 250 }),
      makeHighlight({ color: "purple", y: 300 }),
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 밑줄 (underline)", () => {
  it("밑줄 어노테이션이 적용되면 PDF에 라인이 추가된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeUnderline()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("밑줄은 요소의 하단에 그려진다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // y=100, height=30 → 밑줄 Y = pageHeight - (100 + 30)
    const result = await annotatePdf(
      [file],
      { annotations: [makeUnderline({ y: 100, height: 30 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 취소선 (strikethrough)", () => {
  it("취소선 어노테이션이 적용되면 PDF에 라인이 추가된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeStrikethrough()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("취소선은 요소의 중간에 그려진다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // y=200, height=40 → 중간 Y = pageHeight - (200 + 40/2)
    const result = await annotatePdf(
      [file],
      { annotations: [makeStrikethrough({ y: 200, height: 40 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 사각형 (rectangle)", () => {
  it("사각형 어노테이션이 적용되면 PDF에 사각형이 추가된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeRectangle()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("fillColor가 transparent이면 채우기가 적용되지 않는다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeRectangle({ fillColor: "transparent" })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("fillColor가 지정되면 채우기가 적용된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeRectangle({ fillColor: "#FF000080" })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 타원 (ellipse)", () => {
  it("타원 어노테이션이 적용되면 PDF에 타원이 추가된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeEllipse()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("타원 fillColor가 transparent이면 채우기 없이 테두리만", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeEllipse({ fillColor: "transparent" })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("타원 중심 좌표가 올바르게 변환된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // x=50, y=100, width=100, height=80
    // cx=100, cy=140, pdfCy = 842 - 140 = 702
    const result = await annotatePdf(
      [file],
      { annotations: [makeEllipse({ x: 50, y: 100, width: 100, height: 80 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 화살표 (arrow)", () => {
  it("화살표 어노테이션이 적용되면 PDF에 라인 + 삼각형이 추가된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeArrow()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("화살표 길이가 0인 경우에도 에러 없이 처리한다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // 시작점 = 끝점 → len = 0, 화살머리 건너뜀
    const result = await annotatePdf(
      [file],
      { annotations: [makeArrow({ points: [100, 100, 100, 100] })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 자유 곡선 (freehand)", () => {
  it("프리핸드 어노테이션이 적용되면 PDF에 연결된 라인이 추가된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeFreehand()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("포인트가 많은 프리핸드도 처리된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // 100개의 점 (50개 세그먼트)
    const points: number[] = [];
    for (let i = 0; i < 100; i++) {
      points.push(10 + i * 3, 100 + Math.sin(i) * 20);
    }

    const result = await annotatePdf(
      [file],
      { annotations: [makeFreehand({ points })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("포인트가 2개뿐이면 (단일 점) 라인이 0개여도 에러 없음", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // 좌표 1개 = points [x, y] → 루프가 실행되지 않음
    const result = await annotatePdf(
      [file],
      { annotations: [makeFreehand({ points: [10, 20] })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 텍스트 박스 (text-box)", () => {
  it("Latin 텍스트가 표준 폰트로 그려진다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ content: "Hello World" })] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("빈 content면 텍스트가 그려지지 않는다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ content: "" })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("공백만 있는 content면 텍스트가 그려지지 않는다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ content: "   " })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("backgroundColor가 지정되면 배경 사각형이 그려진다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ backgroundColor: "#FFFF00" })] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("borderColor가 지정되면 테두리 사각형이 그려진다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ borderColor: "#000000" })] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("bold, italic 조합이 올바른 폰트로 매핑된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const annotations = [
      makeTextBox({ content: "Normal", bold: false, italic: false, y: 50 }),
      makeTextBox({ content: "Bold", bold: true, italic: false, y: 100 }),
      makeTextBox({ content: "Italic", bold: false, italic: true, y: 150 }),
      makeTextBox({ content: "Bold Italic", bold: true, italic: true, y: 200 }),
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("center/right 정렬도 에러 없이 처리된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const annotations = [
      makeTextBox({ content: "Left", align: "left", y: 50 }),
      makeTextBox({ content: "Center", align: "center", y: 100 }),
      makeTextBox({ content: "Right", align: "right", y: 150 }),
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("여러 줄 텍스트가 처리된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      {
        annotations: [
          makeTextBox({
            content: "Line 1\nLine 2\nLine 3",
            height: 100,
          }),
        ],
      },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — CJK 텍스트 (canvas→image 폴백)", () => {
  it("한글 텍스트는 canvas→image 방식으로 렌더링된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ content: "안녕하세요" })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
    // canvas mock을 통해 이미지가 임베드됨
    expect(document.createElement).toHaveBeenCalledWith("canvas");
  });

  it("일본어 텍스트도 canvas→image 폴백을 사용한다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ content: "こんにちは" })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("중국어 텍스트도 canvas→image 폴백을 사용한다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeTextBox({ content: "你好世界" })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 스탬프 (stamp)", () => {
  it("스탬프 어노테이션이 적용되면 PDF에 이미지가 임베드된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeStamp()] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("다양한 스탬프 종류가 모두 처리된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const kinds = [
      "approved", "rejected", "confidential", "draft",
      "final", "void", "not-approved", "for-review",
    ] as const;

    const annotations = kinds.map((kind, i) =>
      makeStamp({ stampKind: kind, y: i * 60 }),
    );

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 여러 페이지에 어노테이션", () => {
  it("서로 다른 페이지에 어노테이션이 각각 적용된다", async () => {
    const file = await createMarkedPdf(3);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const annotations: AnnotateElement[] = [
      makeHighlight({ pageIndex: 0, y: 50 }),
      makeUnderline({ pageIndex: 1, y: 100 }),
      makeRectangle({ pageIndex: 2, y: 150 }),
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(3);
    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("같은 페이지에 여러 종류의 어노테이션이 모두 적용된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const annotations: AnnotateElement[] = [
      makeHighlight({ y: 50 }),
      makeUnderline({ y: 100 }),
      makeStrikethrough({ y: 150 }),
      makeRectangle({ y: 200 }),
      makeEllipse({ y: 300 }),
      makeArrow(),
      makeFreehand(),
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("범위 밖 pageIndex는 무시된다 (에러 없음)", async () => {
    const file = await createMarkedPdf(2);
    const { onProgress } = createProgressTracker();

    const annotations: AnnotateElement[] = [
      makeHighlight({ pageIndex: 0 }),
      makeHighlight({ pageIndex: 99 }),  // 존재하지 않는 페이지
      makeHighlight({ pageIndex: -1 }),  // 음수 인덱스
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(2);
  });
});

describe("annotate-pdf — 좌표 변환 (Konva Y-down → PDF Y-up)", () => {
  it("Y좌표가 올바르게 변환된다 — 결과 PDF가 유효하다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // pageHeight = 842, y=100, height=30
    // toPdfY(100, 30, 842) = 842 - 100 - 30 = 712
    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight({ y: 100, height: 30 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
    // 결과를 다시 저장해도 유효해야 함
    const bytes = await pdf.save();
    expect(bytes.length).toBeGreaterThan(0);
  });

  it("페이지 하단 y=0에 어노테이션 → PDF 상단에 렌더링", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // y=0, height=30 → toPdfY = 842 - 0 - 30 = 812 (PDF 상단 근처)
    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight({ y: 0, height: 30 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("페이지 하단 근처에 어노테이션 → PDF 하단에 렌더링", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    // y=810, height=30 → toPdfY = 842 - 810 - 30 = 2 (PDF 하단 근처)
    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight({ y: 810, height: 30 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — opacity 처리", () => {
  it("커스텀 opacity가 적용된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const annotations: AnnotateElement[] = [
      makeHighlight({ opacity: 0.5, y: 50 }),
      makeRectangle({ opacity: 0.3, y: 150 }),
      makeEllipse({ opacity: 0.7, y: 250 }),
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("opacity=0인 어노테이션도 에러 없이 처리된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight({ opacity: 0 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("opacity=1인 어노테이션은 완전 불투명하다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeRectangle({ opacity: 1 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — rotation 처리", () => {
  it("사각형에 rotation이 적용된다", async () => {
    const file = await createMarkedPdf(1);
    const origLen = await getOriginalByteLength(file);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeRectangle({ rotation: 45 })] },
      onProgress,
    );

    const resultLen = (await result.blob.arrayBuffer()).byteLength;
    expect(resultLen).toBeGreaterThan(origLen);
  });

  it("텍스트 박스에 rotation이 적용된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      {
        annotations: [
          makeTextBox({
            content: "Rotated Text",
            rotation: 30,
            backgroundColor: "#FFFF00",
          }),
        ],
      },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("스탬프에 rotation이 적용된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeStamp({ rotation: -15 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });

  it("rotation=0이면 회전 없이 처리된다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeRectangle({ rotation: 0 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(1);
  });
});

describe("annotate-pdf — 출력 포맷", () => {
  it("파일명이 _annotated.pdf로 끝난다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight()] },
      onProgress,
    );

    expect(result.filename).toBe("marked-1p_annotated.pdf");
  });

  it("blob 타입이 application/pdf이다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight()] },
      onProgress,
    );

    expect(result.blob.type).toBe("application/pdf");
  });

  it("size가 blob.size와 일치한다", async () => {
    const file = await createMarkedPdf(1);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight()] },
      onProgress,
    );

    expect(result.size).toBe(result.blob.size);
  });

  it("pageCount가 원본과 같다", async () => {
    const file = await createMarkedPdf(5);
    const { onProgress } = createProgressTracker();

    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight({ pageIndex: 2 })] },
      onProgress,
    );

    expect(result.pageCount).toBe(5);
  });
});

describe("annotate-pdf — 에러 처리", () => {
  it("파일 없으면 에러", async () => {
    const { onProgress } = createProgressTracker();

    await expect(
      annotatePdf([], { annotations: [makeHighlight()] }, onProgress),
    ).rejects.toThrow("No file provided");
  });
});

describe("annotate-pdf — progress 콜백", () => {
  it("progress가 호출된다", async () => {
    const file = await createMarkedPdf(2);
    const { values, onProgress } = createProgressTracker();

    await annotatePdf(
      [file],
      { annotations: [makeHighlight({ pageIndex: 0 })] },
      onProgress,
    );

    expect(values.length).toBeGreaterThan(0);
    expect(values[values.length - 1]).toBe(100);
  });

  it("progress가 단조 증가한다", async () => {
    const file = await createMarkedPdf(3);
    const { values, onProgress } = createProgressTracker();

    const annotations: AnnotateElement[] = [
      makeHighlight({ pageIndex: 0 }),
      makeUnderline({ pageIndex: 1 }),
      makeRectangle({ pageIndex: 2 }),
    ];

    await annotatePdf([file], { annotations }, onProgress);

    for (let i = 1; i < values.length; i++) {
      expect(values[i]).toBeGreaterThanOrEqual(values[i - 1]);
    }
    expect(values[values.length - 1]).toBe(100);
  });

  it("progress 5, 15, 25 시작 후 90, 100으로 끝난다", async () => {
    const file = await createMarkedPdf(1);
    const { values, onProgress } = createProgressTracker();

    await annotatePdf(
      [file],
      { annotations: [makeHighlight()] },
      onProgress,
    );

    expect(values[0]).toBe(5);
    expect(values).toContain(15);
    expect(values).toContain(25);
    expect(values).toContain(90);
    expect(values).toContain(100);
  });
});

describe("annotate-pdf — 결과 PDF 재사용 가능", () => {
  it("결과 PDF가 유효하고 다시 로드·저장할 수 있다", async () => {
    const file = await createMarkedPdf(3);
    const { onProgress } = createProgressTracker();

    const annotations: AnnotateElement[] = [
      makeHighlight({ pageIndex: 0 }),
      makeRectangle({ pageIndex: 1 }),
      makeEllipse({ pageIndex: 2 }),
    ];

    const result = await annotatePdf([file], { annotations }, onProgress);

    const pdf = await resultToPdf(result.blob);
    expect(pdf.getPageCount()).toBe(3);

    // 다시 저장 가능해야 함
    const bytes2 = await pdf.save();
    expect(bytes2.length).toBeGreaterThan(0);
  });

  it("페이지 크기가 보존된다", async () => {
    const file = await createMarkedPdf(2);
    const { onProgress } = createProgressTracker();

    const origPdf = await PDFDocument.load(await file.arrayBuffer());
    const origSizes = origPdf.getPages().map((p) => p.getSize());

    const result = await annotatePdf(
      [file],
      { annotations: [makeHighlight({ pageIndex: 0 })] },
      onProgress,
    );

    const pdf = await resultToPdf(result.blob);
    for (let i = 0; i < pdf.getPageCount(); i++) {
      const { width, height } = pdf.getPage(i).getSize();
      expect(Math.round(width)).toBe(Math.round(origSizes[i].width));
      expect(Math.round(height)).toBe(Math.round(origSizes[i].height));
    }
  });
});
